# Generated by Django 3.0.4 on 2020-05-05 23:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orgApp', '0015_organisation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgproject',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orgproject',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orgproject',
            name='budget',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orgproject',
            name='duration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orgproject',
            name='selected_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orgproject',
            name='status',
            field=models.BooleanField(default=False, verbose_name='status'),
        ),
    ]
