# Generated by Django 3.0.4 on 2020-05-06 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgApp', '0016_auto_20200506_0511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgproject',
            old_name='name',
            new_name='project_name',
        ),
    ]
