# Generated by Django 3.0.4 on 2020-05-06 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orgApp', '0017_auto_20200507_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgproject',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
