# Generated by Django 3.0.4 on 2020-05-06 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgApp', '0018_orgproject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgproject',
            name='name',
        ),
    ]
