# Generated by Django 3.0.4 on 2020-05-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgApp', '0019_remove_orgproject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgproject',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orgproject',
            name='start_date',
            field=models.DateField(),
        ),
    ]
