# Generated by Django 3.0.4 on 2020-05-08 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgApp', '0020_auto_20200507_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgproject',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_projects', to='orgApp.Organisation'),
        ),
    ]
