# Generated by Django 3.0.4 on 2020-05-08 23:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgApp', '0021_auto_20200508_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='about',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
