# Generated by Django 3.0.4 on 2020-05-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgApp', '0023_auto_20200509_0627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgproject',
            options={'get_latest_by': 'created_date'},
        ),
    ]
